version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  mcp-server:
    build: .
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_DATABASE: testdb
      MYSQL_CHARSET: utf8mb4
      MYSQL_AUTOCOMMIT: "true"
      MYSQL_POOL_SIZE: 5
      MYSQL_SSL_MODE: DISABLED
      GITHUB_ADMINS: your_github_username
      GITHUB_WRITERS: ""
      GITHUB_READERS: ""
      ENABLE_MONITORING: "false"
    depends_on:
      - mysql
    volumes:
      - ./logs:/app/logs
    stdin_open: true
    tty: true

volumes:
  mysql_data:
