name = "mysql-mcp-server"
main = "main.py"
compatibility_date = "2024-01-01"
compatibility_flags = ["python_workers"]

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }

# Database configuration (use secrets for sensitive data)
[vars]
MYSQL_HOST = "your-mysql-host"
MYSQL_PORT = "3306"
MYSQL_DATABASE = "your-database"
MYSQL_CHARSET = "utf8mb4"
MYSQL_AUTOCOMMIT = "true"
MYSQL_POOL_SIZE = "5"
MYSQL_SSL_MODE = "REQUIRED"

# Use wrangler secrets for sensitive data:
# wrangler secret put MYSQL_USER
# wrangler secret put MYSQL_PASSWORD
# wrangler secret put GITHUB_ADMINS
# wrangler secret put GITHUB_WRITERS
# wrangler secret put GITHUB_READERS
# wrangler secret put SENTRY_DSN

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"
